load(
    "@rules_python//python:defs.bzl",
    "py_library",
)

package(default_visibility = ["//visibility:public"])

py_library(
    name = "remote_bitbang",
    srcs = ["remote_bitbang.py"],
    deps = [
        "//pip:nmigen",
    ],
)
